version: 2

project_name: drillbit

builds:
  - id: drillbit
    main: .
    binary: drillbit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: default
    formats: ['zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: jclement
    name: drillbit
  draft: false
  prerelease: auto

dockers:
  - image_templates:
      - "ghcr.io/jclement/drillbit:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
  - image_templates:
      - "ghcr.io/jclement/drillbit:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/jclement/drillbit:{{ .Version }}"
    image_templates:
      - "ghcr.io/jclement/drillbit:{{ .Version }}-amd64"
      - "ghcr.io/jclement/drillbit:{{ .Version }}-arm64"
  - name_template: "ghcr.io/jclement/drillbit:latest"
    image_templates:
      - "ghcr.io/jclement/drillbit:{{ .Version }}-amd64"
      - "ghcr.io/jclement/drillbit:{{ .Version }}-arm64"
