package main

import "math/rand"

var taglines = []string{
	"drilling into your data since just now",
	"sudo make me a sandwich",
	"it's not a bug, it's a feature",
	"have you tried turning it off and on again?",
	"tunneling through the bureaucracy",
	"your DBA doesn't need to know",
	"SELECT * FROM motivation WHERE monday = true",
	"powered by caffeine and SSH keys",
	"because psql is too mainstream",
	"now with 100% more tunnels",
	"the bits must flow",
	"connecting things that probably shouldn't be connected",
	"trust me, I'm an engineer",
	"rm -rf doubts",
	"works on my machine",
	"no databases were harmed in the making of this tunnel",
	"tunnels: like VPNs but with more anxiety",
	"one does not simply query production",
	"may your queries be fast and your indices clustered",
	"establishing a secure-ish connection",
	"hold my beer and watch this query",
	"making SSH sexy since 2025",
	"your friendly neighborhood tunnel manager",
	"ctrl+c to abandon all hope",
	"postgres whisperer",
	"because docker exec is for amateurs",
	"port forwarding with style",
	"shoveling data through encrypted pipes",
	"NULL is not nothing, it's the absence of something",
	"in transactions we trust",
	"Bobby Tables approved",
	"warranty void if used in production",
	"now with extra ACID compliance",
	"the tunnel at the end of the light",
	"ssh -N -L vibes:good localhost",
	"0 bugs found (we didn't look)",
	"INSERT INTO tunnels VALUES ('this one')",
	"your packets, our problem",
	"like a VPN, but with personality",
	"autocommit your feelings",
	"this is fine.jpg",
	"connections: it's what we do",
	"have you indexed that?",
	"EXPLAIN ANALYZE your life choices",
	"DROP TABLE IF EXISTS problems",
	"ALTER TABLE mood SET happy = true",
	"faster than a speeding SELECT *",
	"making ops people nervous since day one",
	"you can't spell tunnel without 'fun'... wait",
	"proudly over-engineered",
	"dig baby dig",
	"bits go in, bits come out",
	"now accepting connections",
	"the quick brown fox jumped over the lazy DBA",
	"not all heroes wear capes, some write tunnels",
	"do you even JOIN?",
	"lateral thinking, lateral joins",
	"permission granted",
	"BEGIN; -- here goes nothing",
	"your secrets are safe in transit",
	"more reliable than your last relationship",
	"VACUUM FULL your worries away",
	"drill sergeant reporting for duty",
	"where we're going, we don't need GUIs",
	"ssh into the void",
	"connections are temporary, data is forever",
	"spinning up the hamster wheel",
	"reticulating splines",
	"contacting mothership",
	"negotiating with firewalls",
	"please hold, your data is important to us",
	"no cap, just TCP",
	"always be connecting",
	"access granted, proceed with caution",
	"entering the matrix",
	"the truth is in the data",
	"drilling responsibly since launch",
	"sudo drillbit --with-confidence",
	"127.0.0.1 sweet 127.0.0.1",
	"there's no place like localhost",
	"I see your schema and raise you an index",
	"COMMIT or ROLLBACK, there is no try",
	"it's turtles all the way down",
	"leaking memory, not data",
	"may the --force be with you",
	"chmod 777 your heart",
	"segfault in feelings.c",
	"piping hot data, served fresh",
	"tunneling through spacetime",
	"do not feed the ORM",
	"tabs vs spaces? we use tunnels",
	"git push --force your way through",
	"you miss 100% of the queries you don't run",
	"keep calm and REINDEX",
	"making TCP/IP personal again",
	"handshake complete",
	"certified pre-owned connections",
	"organic, free-range, locally-sourced tunnels",
	"batteries not included, SSH keys required",
	"caution: may contain traces of SQL",
	"void where prohibited by network policy",
}

func randomTagline() string {
	return taglines[rand.Intn(len(taglines))]
}
